# This is a sample Jupyter Notebook

Below is an example of a code cell.
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [2]:
print("Hello World!")
print(7*7)

Hello World!
49

# Key Data structures in Pandas
* Series
* DataFrame

In [6]:
import pandas as pd

In [12]:
S=pd.Series([1,2,3,4,5])

In [15]:
S

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
import pandas as pd
print(pd.__version__)

2.3.2

In [17]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Marks": [90, 85, 95]
})

In [18]:
df

  Name  Marks
0    A     90
1    B     85
2    C     95

In [19]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

       Marks
count    3.0
mean    90.0
std      5.0
min     85.0
25%     87.5
50%     90.0
75%     92.5
max     95.0

In [22]:
ap = pd.Series([10,20,30], index=['a','b','c'])

In [24]:
ap

a    10
b    20
c    30
dtype: int64

How to create a dataframe?

In [29]:
results = pd.DataFrame({"Name": ["Abhishek", "Bhushan", "Kartik","Atharva","Deepak","Dhruv"], "Marks": [90, 85, 95,70,96,100], "Rank": [2,3,4,5,6,1]})

In [30]:
results

       Name  Marks  Rank
0  Abhishek     90     2
1   Bhushan     85     3
2    Kartik     95     4
3   Atharva     70     5
4    Deepak     96     6
5     Dhruv    100     1

In [32]:
results.head()

       Name  Marks  Rank
0  Abhishek     90     2
1   Bhushan     85     3
2    Kartik     95     4
3   Atharva     70     5
4    Deepak     96     6

In [33]:
results.tail()

      Name  Marks  Rank
1  Bhushan     85     3
2   Kartik     95     4
3  Atharva     70     5
4   Deepak     96     6
5    Dhruv    100     1

In [34]:
results.head(2)

       Name  Marks  Rank
0  Abhishek     90     2
1   Bhushan     85     3

In [36]:
results.head(2,5)

TypeError: NDFrame.head() takes from 1 to 2 positional arguments but 3 were given

In [37]:
df=pd.read_csv("data/iris.csv")

In [38]:
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [39]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [40]:
df.head(20)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

In [41]:
df.head(150)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [42]:
df.head(50)

    sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa
20           5.4          3.4           1.7          0.2  Setosa
21           5.1          3.7           1.5          0.4  Setosa
22           4.6          3.6           1.0          0.2  Setosa
23           5.1          3.3           1.7          0.5  Setosa
24           4.8          3.4           1.9          0.2  Setosa
25           5.0          3.0           1.6          0.2  Setosa
26           5.0          3.4           1.6          0.4  Setosa
27           5.2          3.5           1.5          0.2  Setosa
28           5.2          3.4           1.4          0.2  Setosa
29           4.7          3.2           1.6          0.2  Setosa
30           4.8          3.1           1.6          0.2  Setosa
31           5.4          3.4           1.5          0.4  Setosa
32           5.2          4.1           1.5          0.1  Setosa
33           5.5          4.2           1.4          0.2  Setosa
34           4.9          3.1           1.5          0.2  Setosa
35           5.0          3.2           1.2          0.2  Setosa
36           5.5          3.5           1.3          0.2  Setosa
37           4.9          3.6           1.4          0.1  Setosa
38           4.4          3.0           1.3          0.2  Setosa
39           5.1          3.4           1.5          0.2  Setosa
40           5.0          3.5           1.3          0.3  Setosa
41           4.5          2.3           1.3          0.3  Setosa
42           4.4          3.2           1.3          0.2  Setosa
43           5.0          3.5           1.6          0.6  Setosa
44           5.1          3.8           1.9          0.4  Setosa
45           4.8          3.0           1.4          0.3  Setosa
46           5.1          3.8           1.6          0.2  Setosa
47           4.6          3.2           1.4          0.2  Setosa
48           5.3          3.7           1.5          0.2  Setosa
49           5.0          3.3           1.4          0.2  Setosa

In [43]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [45]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

Data Selection

In [49]:
df["variety"]

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [53]:
type(df["variety"])

pandas.core.series.Series

In [55]:
df[["variety","sepal.length"]]

       variety  sepal.length
0       Setosa           5.1
1       Setosa           4.9
2       Setosa           4.7
3       Setosa           4.6
4       Setosa           5.0
..         ...           ...
145  Virginica           6.7
146  Virginica           6.3
147  Virginica           6.5
148  Virginica           6.2
149  Virginica           5.9

[150 rows x 2 columns]

In [58]:
df.iloc[0] # prints first row

sepal.length       5.1
sepal.width        3.5
petal.length       1.4
petal.width        0.2
variety         Setosa
Name: 0, dtype: object

In [59]:
type(df.iloc[5]) # prints series as its 1 dimensional datatype

pandas.core.series.Series

In [60]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [63]:
df.rename(columns={"variety":"specie"})

     sepal.length  sepal.width  petal.length  petal.width     specie
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [64]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [66]:
df["sepal.length"]=df["sepal.length"].astype(int) # changes datatype of sepal.length column entries... obv affects the stats

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    int64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(3), int64(1), object(1)
memory usage: 6.0+ KB

In [68]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0             5          3.5           1.4          0.2  Setosa
1             4          3.0           1.4          0.2  Setosa
2             4          3.2           1.3          0.2  Setosa
3             4          3.1           1.5          0.2  Setosa
4             5          3.6           1.4          0.2  Setosa

In [69]:
df.describe() # effect of changing datatype of one column can be seen here

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.386667     3.057333      3.758000     1.199333
std        0.841752     0.435866      1.765298     0.762238
min        4.000000     2.000000      1.000000     0.100000
25%        5.000000     2.800000      1.600000     0.300000
50%        5.000000     3.000000      4.350000     1.300000
75%        6.000000     3.300000      5.100000     1.800000
max        7.000000     4.400000      6.900000     2.500000

In [70]:
len(df)

150

In [74]:
df["extra column"]=[(df["sepal.length"][i]+df["sepal.width"][i]+df["petal.length"][i]+df["petal.width"][i])/4 for i in range (len(df))]

In [75]:
df

,sepal.length,sepal.width,petal.length,petal.width,variety,extra column
0,5,3.5,1.4,0.2,Setosa,2.525
1,4,3.0,1.4,0.2,Setosa,2.150
2,4,3.2,1.3,0.2,Setosa,2.175
3,4,3.1,1.5,0.2,Setosa,2.200
4,5,3.6,1.4,0.2,Setosa,2.550
...,...,...,...,...,...,...
145,6,3.0,5.2,2.3,Virginica,4.125
146,6,2.5,5.0,1.9,Virginica,3.850
147,6,3.0,5.2,2.0,Virginica,4.050
148,6,3.4,5.4,2.3,Virginica,4.275
149,5,3.0,5.1,1.8,Virginica,3.725

In [76]:
df.describe()

       sepal.length  sepal.width  petal.length  petal.width  extra column
count    150.000000   150.000000    150.000000   150.000000    150.000000
mean       5.386667     3.057333      3.758000     1.199333      3.350333
std        0.841752     0.435866      1.765298     0.762238      0.773372
min        4.000000     2.000000      1.000000     0.100000      1.975000
25%        5.000000     2.800000      1.600000     0.300000      2.606250
50%        5.000000     3.000000      4.350000     1.300000      3.462500
75%        6.000000     3.300000      5.100000     1.800000      3.918750
max        7.000000     4.400000      6.900000     2.500000      4.925000

In [77]:
def fx(a):
    return a*a

In [78]:
df["squared"]=df["extra column"].apply(fx)

In [79]:
df

,sepal.length,sepal.width,petal.length,petal.width,variety,extra column,squared
0,5,3.5,1.4,0.2,Setosa,2.525,6.375625
1,4,3.0,1.4,0.2,Setosa,2.150,4.622500
2,4,3.2,1.3,0.2,Setosa,2.175,4.730625
3,4,3.1,1.5,0.2,Setosa,2.200,4.840000
4,5,3.6,1.4,0.2,Setosa,2.550,6.502500
...,...,...,...,...,...,...,...
145,6,3.0,5.2,2.3,Virginica,4.125,17.015625
146,6,2.5,5.0,1.9,Virginica,3.850,14.822500
147,6,3.0,5.2,2.0,Virginica,4.050,16.402500
148,6,3.4,5.4,2.3,Virginica,4.275,18.275625
149,5,3.0,5.1,1.8,Virginica,3.725,13.875625

In [80]:
df.to_csv("data/iris_modified.csv") # saves all the additions, but extra index 0,1,2,3 is there so to remove it we go again with following

In [82]:
df.to_csv("data/iris_final.csv",index=False) # all done and clean